name: build
on: [push]
jobs:
  build-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Display node version
        run: node --version
      - name: Display npm version
        run: npm --version
      - name: Install dependencies
        run: npm i
      - name: Build React project
        run: npm run build
        env:
          CI: false
      # - name: Run React tests
      #   run: npm run test
  
  build-zanzibre:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: zanzibre
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get -u all
      - name: Build Go project
        run: go build
