name: build
on: [push]
jobs:
  build-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
        env:
          CI: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: node --version
      - run: npm --version
      - run: npm i
      - run: npm run build
      - run: npm run test
